### PR TITLE
Fix entity's chunk Y-coordinate not updating

### LINKED ISSUE #172: Placing blocks while being in certain positions of the world doesn't work correctly
https://youtu.be/5LsN_iRmz70

### PR DESCRIPTION
**Pull request by bluepilledgreat**
Fixes #172

### CODE REVIEW

**Comment by Vimd0** [comment]
> Fixes #172

OMG thank you! This has been a bug for the longest time 😭

File: source/world/level/Level.cpp [hunk 1]
```diff
@@ -1558,15 +1558,20 @@ void Level::tick(Entity* pEnt, bool b)
 
 		if (hasChunk(cp))
 		{
-			pEnt->m_bInAChunk = true;
```
Comment (BrentDaMage) [inline source/world/level/Level.cpp:1561]: Why remove this?

File: source/world/level/levelgen/chunk/LevelChunk.cpp [hunk 2]
```diff
@@ -302,6 +302,43 @@ void LevelChunk::addEntity(Entity* pEnt)
...
+	}
+
+	std::vector<Entity*>::iterator it = std::find(m_entities[oldYCoord].begin(), m_entities[oldYCoord].end(), pEnt);
+	if (it != m_entities[oldYCoord].end())
+	{
+		m_entities[oldYCoord].erase(it);
+	}
+	else
+	{
+		assert(false);
```
Comment (BrentDaMage) [inline source/world/level/levelgen/chunk/LevelChunk.cpp:337]: Did you forget to return here?

File: source/world/level/levelgen/chunk/LevelChunk.cpp [hunk 3]
```diff
@@ -302,6 +302,43 @@ void LevelChunk::addEntity(Entity* pEnt)
...
+		return;
+	}
+
+	if (oldYCoord < 0 || oldYCoord > 7)
+	{
+		assert(false);
+		return;
+	}
+
+	std::vector<Entity*>::iterator it = std::find(m_entities[oldYCoord].begin(), m_entities[oldYCoord].end(), pEnt);
```
Comment (BrentDaMage) [inline source/world/level/levelgen/chunk/LevelChunk.cpp]: Improve readability by making local variables for `m_entities[oldYCoord]` and `m_entities[newYCoord]` std::vector references. Perhaps call them `newTerrainLayer` and `oldTerrainLayer`?

File: source/world/level/Level.cpp (hunk 1 above)
Comment (bluepilledgreat) [reply source/world/level/Level.cpp:1561]: `addEntity` sets it to true anyways, so there is no real point in doing it here

File: source/world/level/levelgen/chunk/LevelChunk.cpp (hunk 2 above)
Comment (bluepilledgreat) [reply source/world/level/levelgen/chunk/LevelChunk.cpp:337]: Did not forget, it not being in the original vector is not intended but it shouldn't mean we should just entirely stop as it should be in one of the vectors
